development:
  adapter: mysql2
  encoding: utf8
  database: starci_development
  username: starc
  password: starc

test:
  adapter: mysql2
  encoding: utf8
  database: starci_test
  username: starc
  password: starc
