# Example file. Rename this to s3.yml and put in valid credentials for localhost use.
# NEVER commit the s3.yml file which is in .gitignore anyways.

development:
  bucket: 'starostiprijazno-dev'
  access_key_id: 'AKIAJH237ZG7CDV3YRNA'
  secret_access_key: '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'

test: development  
  
production: 
  bucket: 'starostiprijazno'
  access_key_id: 'AKIAJH237ZG7CDV3YRNA'
  secret_access_key: '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'
